language: java
sudo: required
jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=LATEST-TRUNK-SNAPSHOT
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  - IDEA_VERSION=IC-2018.1 # Stable
  - IDEA_VERSION=IC-2017.3 # Previous
  - IDEA_VERSION=IC-2017.2 # Old

# Code Coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
